CONF_CAMERA_ID = "camera_id"
CONF_TASK_FILE_PATH = "task_file_path"
CONF_NATURE_REMO = "nature_remo"
CONF_ACCESS_TOKEN = "access_token"
CONF_TARGET_NICKNAME = "target_nickname"
CONF_INTERVAL_TIME = "interval_time"
